# Generated by Django 5.2.14 on 2026-05-11 19:39

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='compliance_note',
            field=models.TextField(default='This website is intended for informational purposes and does not create an advocate-client relationship.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='court_coverage',
            field=wagtail.fields.StreamField([('court', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 90, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('detail', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='credibility_points',
            field=wagtail.fields.StreamField([('point', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 90})}, help_text='Short trust markers shown below the hero section.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='firm_overview',
            field=wagtail.fields.RichTextField(blank=True, default='<p>Ajmani and Law Partners combines trial-readiness with practical guidance. The firm is positioned to represent clients in district courts, the Delhi High Court, and the Supreme Court of India while keeping communication direct and client-focused.</p>'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='firm_overview_title',
            field=models.CharField(default='A litigation-first firm for Delhi matters', max_length=90),
        ),
        migrations.AddField(
            model_name='homepage',
            name='founder_bio',
            field=wagtail.fields.RichTextField(blank=True, default="<p>Share the founder's courtroom experience, notable appearances, sector knowledge, and the kind of matters the firm is best known for.</p>"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='founder_designation',
            field=models.CharField(default='Founding Partner', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='founder_highlights',
            field=wagtail.fields.StreamField([('highlight', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100})}, help_text='Examples: Client-first communication, Trial strategy, Strong briefing discipline.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='founder_name',
            field=models.CharField(default='Advocate Ajmani', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(default='Ajmani and Law Partners helps individuals, families, and businesses navigate complex disputes with clear advice, responsive counsel, and disciplined courtroom strategy.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Trusted representation across Delhi district, high and supreme courts.', max_length=140),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_kicker',
            field=models.CharField(default='Delhi Litigation Counsel', help_text='Short line above the main headline.', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_intro',
            field=models.TextField(default='Publish short, useful updates on new judgments, procedural changes, and practical legal takeaways.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='newsletter_title',
            field=models.CharField(default='Monthly legal newsletters', max_length=90),
        ),
        migrations.AddField(
            model_name='homepage',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='practice_areas',
            field=wagtail.fields.StreamField([('practice', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 90, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 260, 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_label',
            field=models.CharField(default='Book a consultation', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_link',
            field=models.CharField(default='#contact', help_text='Use a full URL or an in-page anchor such as #contact.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_label',
            field=models.CharField(default='Read newsletters', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_link',
            field=models.CharField(default='#newsletters', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 4)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'max_length': 320, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'max_value': 5, 'min_value': 1, 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Google Reviews', 'max_length': 60, 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('quote', 0), ('author', 1), ('rating', 2), ('source', 3)]], {})}),
        ),
    ]
