# Generated by Django 5.2.14 on 2026-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_compliance_note_homepage_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='founder_linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
