# Generated by Django 5.2.14 on 2026-05-11 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_founder_linkedin_url'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleReviewFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='ajmani-homepage', max_length=80, unique=True)),
                ('place_id', models.CharField(blank=True, max_length=180)),
                ('place_name', models.CharField(blank=True, max_length=255)),
                ('average_rating', models.FloatField(default=0)),
                ('total_review_count', models.PositiveIntegerField(default=0)),
                ('google_maps_url', models.URLField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Google review feed',
                'verbose_name_plural': 'Google review feeds',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_emailed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='founder_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_business_share_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_maps_embed_query',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_maps_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='google_reviews_query',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_default_message',
            field=models.TextField(blank=True, default='Hello, I would like to discuss a legal matter with Ajmani and Law Partners.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=255, unique=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_url', models.URLField(blank=True)),
                ('author_photo_url', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0)),
                ('relative_publish_time_description', models.CharField(blank=True, max_length=120)),
                ('review_text', models.TextField(blank=True)),
                ('review_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.googlereviewfeed')),
            ],
            options={
                'ordering': ['display_order', '-published_at', '-id'],
            },
        ),
    ]
