# Generated by Django 5.2.14 on 2026-05-23 19:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactinquiry_googlereviewfeed_newslettersubscriber_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='Articles, legal explainers, case-note style commentary, and practical writing from Ajmani and Law Partners.')),
            ],
            options={
                'verbose_name': 'Blog index page',
                'verbose_name_plural': 'Blog index pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField(verbose_name='Publication date')),
                ('summary', models.TextField(blank=True, max_length=280)),
                ('author_name', models.CharField(blank=True, help_text='Example: Editorial Team or a junior associate.', max_length=120)),
                ('body', wagtail.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Blog page',
                'verbose_name_plural': 'Blog pages',
                'ordering': ['-publication_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default="Reach out for consultations, updates on an existing matter, or general questions about the firm's services.")),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact page',
                'verbose_name_plural': 'Contact pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Short introduction shown near the top of the page.')),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Optional overview content for this section landing page.')),
            ],
            options={
                'verbose_name': 'Section index page',
                'verbose_name_plural': 'Section index pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, max_length=320)),
                ('body', wagtail.fields.RichTextField()),
                ('highlights', wagtail.fields.StreamField([('highlight', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 110})}, help_text='Optional bullet points for the side panel.')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Content page',
                'verbose_name_plural': 'Content pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
