# Generated by Django 5.2.14 on 2026-05-11 19:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='A running archive of monthly newsletters covering legal updates, litigation trends, and concise client-facing commentary.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsletterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField(verbose_name='Publication date')),
                ('issue_label', models.CharField(blank=True, help_text='Examples: May 2026 issue, Volume 1 Issue 3.', max_length=80)),
                ('summary', models.TextField(blank=True, max_length=260)),
                ('body', wagtail.fields.RichTextField()),
            ],
            options={
                'ordering': ['-publication_date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
