# Generated by Django 5.2.14 on 2026-05-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpage',
            name='email_subject_override',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='send_to_subscribers_on_publish',
            field=models.BooleanField(default=True, help_text='When this issue is published for the first time, send it to active newsletter subscribers.'),
        ),
    ]
