# Generated by Django 5.2.14 on 2026-05-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_newsletterpage_email_subject_override_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpage',
            name='pdf_document',
            field=models.ForeignKey(blank=True, help_text='Optional PDF version of this newsletter issue for direct download or reading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
